### PR TITLE
[test] prepend 0x to address

### PR DESCRIPTION
**Pull request by jiangying000**
## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

### CODE REVIEW

**Comment by jiangying000** [comment]
还有很多测试没过，一下子修估计review 不过来， 分成多个pr

**Comment by jiangying000** [comment]
relate to #19

**Comment by nkysg** [comment]
这里可以写下starcoin-main的分支都需要前面加0x的原因

**Review by jolestar — APPROVED** [review]

**Comment by jiangying000** [comment]
> 这里可以写下starcoin-main的分支都需要前面加0x的原因

应该和 #10 #12 有关， starcoin-main 好像会在输出地址时输出全长的address，并且前面会有0x

**Comment by nkysg** [comment]
https://github.com/starcoinorg/move/blob/starcoin-main/language/move-core/types/src/account_address.rs#L173
```rust
impl fmt::Display for AccountAddress {
    fn fmt(&self, f: &mut fmt::Formatter) -> std::fmt::Result {
        // Forward to the LowerHex impl with a "0x" prepended (the # flag).
        write!(f, "{:#x}", self)
    }
}
```
这里

**Comment by jiangying000** [comment]
> https://github.com/starcoinorg/move/blob/starcoin-main/language/move-core/types/src/account_address.rs#L173
> ```rust
> impl fmt::Display for AccountAddress {
>     fn fmt(&self, f: &mut fmt::Formatter) -> std::fmt::Result {
>         // Forward to the LowerHex impl with a "0x" prepended (the # flag).
>         write!(f, "{:#x}", self)
>     }
> }
> ```
> 这里

和这个有关吗 2个0x
https://github.com/starcoinorg/move/pull/12#discussion_r975054701

**Comment by nkysg** [comment]
> > https://github.com/starcoinorg/move/blob/starcoin-main/language/move-core/types/src/account_address.rs#L173
> > ```rust
> > impl fmt::Display for AccountAddress {
> >     fn fmt(&self, f: &mut fmt::Formatter) -> std::fmt::Result {
> >         // Forward to the LowerHex impl with a "0x" prepended (the # flag).
> >         write!(f, "{:#x}", self)
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这里
> 
> 和这个有关吗 2个0x [#12 (comment)](https://github.com/starcoinorg/move/pull/12#discussion_r975054701)

感觉有关，这个原因我们也再查下

**Pull request merged**
